### ISSUE TITLE
acquireTokenSilent Prompts Error To refresh token

### ISSUE THREAD

**Issue by vikasgrover33** [AzureADQuickStarts/B2C-NativeClient-Android#2]

**Comment by vikasgrover33** [comment]
E/Oauth: SERVER_INVALID_JSON_RESPONSE:2016-01-29 15:15:28-39754e43-808c-4fb0-a97c-6f867d30c663-Value Bad of type java.lang.String cannot be converted to JSONObject ver:2.0.1-alpha 
                                                                     org.json.JSONException: Value Bad of type java.lang.String cannot be converted to JSONObject
                                                                         at org.json.JSON.typeMismatch(JSON.java:111)
                                                                         at org.json.JSONObject.<init>(JSONObject.java:159)
                                                                         at org.json.JSONObject.<init>(JSONObject.java:172)
                                                                         at com.microsoft.aad.adal.Oauth2.extractJsonObjects(Oauth2.java:352)
                                                                         at com.microsoft.aad.adal.Oauth2.processTokenResponse(Oauth2.java:594)
                                                                         at com.microsoft.aad.adal.Oauth2.postMessage(Oauth2.java:520)
                                                                         at com.microsoft.aad.adal.Oauth2.refreshToken(Oauth2.java:384)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1447)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1186)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1148)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1135)
                                                                         at com.microsoft.aad.adal.AuthenticationContext.refreshToken(AuthenticationContext.java:1474)
                                                                     	at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.

**Comment by vikasgrover33** [comment]
{"error":"invalid_request","error_description":"AADSTS50091: Passed query string length exceeds supported limit. encodedRequest=\"rQIIAV2Wuc7tBhWFc-9_xZBIcAVCSkGRggIh-Zfngc728fE8H9vHbizP9vE8-7ijyQNEQqLgJaBA4hWoopSUNEAk3oCCP6JBlHstrWZrf0v708_gV_AVAqJmKKNfvbwNv_4FEec4SSYZQEIIBaBJRAIUQkEACOdpjOcknuLE9JNPP375ux__9s9_P-gv__2vL_70mz_88x_v3n39_t1f33-m0-tSwre-zrq_vf-cbaqsW-gudeZs-h_rq5eXx7589fLTPvpOe52yfMrmcvnO--PLz8vnkE3JGmcxnLz2XVslUz_3-fKa9O1fXn7WD1lXpV_0ed5UXRZGSZLN8zcv3_uv_s3Lj_7f-f4w9XnVZF9_-PDth09_8P7jJ5-_--KTX77_9oe__5g9pSnyzEqvpEfCN4sPU8_AJXf9JkLqgz40W5zFLmiSSsTFB7eqrES9vl6QQIKxSJ2SMoodu32VLq6FMAU-YlIcwlxLs0Wx1YsiLlIJsjvlHM6uw9FCOwfglduqcYkCRed1WIE0y_wj3syYXCm2IomUXmtdqWZL8IdUC8xyGU1gGyp02ijtDtYu2yi6lESNPbBLTTMocjGzOo3MpG7LKlQZkxQ3jDsZDkCscIS0uH3il8f9TnEccNLEjWAFnZOC0ACjpD7WKNRa_-K6wVPCA-t6CS-EfTIGqrcbVC0u6aFukWRIzfrnbRGquZeaNJOsNSqP0kN0VgzOtTpRRwrvEh5SLryER7c0LhnaLRoOsByCpMBysVFGsj9LFgFrHdVFVxNflCxwFboAXNdm7EaAoY58BmdkiJpYBuLSl7Ksm4hWeat5PwVHJ5V11av0Lgkd5vYr7GnyBNrlnT0aXDOUVqKW3hvPVoG8kIyiHXP8xJ_zLnFkBWLnpO5U8e7eO52yMT_u_WrJoij2j7IBh3AN7F1QyylgH2rD1RFeIoy0BG25lVOW3tK6vjIVlKy7ChsnmaVc2XaxsbKznD1PE40HN8LwHYNZIydRQvEt2ibS0rdbE_OIh5ijJ9f2cEbygyittO_RCU7gLqlJQlVssk-5esyAQDuc6erNw8nI3oVFwpY5qPHgI066HE1jW2T2OBZH3c34iuaZeR5PhNcKF0hTDqvgKMy3FjMGIQ1v8lwAegocolnxU03fL-cASaT_yDM94dtCgs1tMHD7SPJDd6eYzVRLCjQzXQFzVvqrlu_IpTUHXYOj3qXQGbCArbbgoPFbCAF128bAkBxwdjV1js8LHbUft7BZ9XiOXIy_nrq7nuByiZPJmZINbbiRtEwPECJlo4Rdi65gFG8KJT51JnW0PkFFEdyv_CQH3uNKzNE46IxOAQO4tIElUZa3YIj8YCtEwG-E2gQcN3d8QSn1WfBnOpuEMh5Mod_iIJHut3u-1yQn-s1kRA6Lb82iDMMciXkeFs0pcDHnYtWcGQ-Yz8wFWZ4SejxwURiG_OoNM7-bbGCtKZjRQGTWDQNZ7Krxgrpem1vBjEV_wJZMw0NACx4w8Zy3oURei71UettiuDz2QE5-J2QIFXXdzGGUiBlt2vKWaah6Y46eH7a8ISHwseutFeqOpt5oDUJINek4hT5UIHbDe45g_ttGugvZ0u08cgYiVGkMVw8SFDaPPKR4qPg1zdhgUtUihOJn7GxpvnlPye7GrpsWZ2M2hygu1vb0I9Qg1dEb_c4wJOskMmoXpD2CCvkR5znYiUq3JoPTvjHr-Qdh870jZaybDcGBC6bIwqJrYI0MQ86Fs0D3JApzgdQ7kHpg0rRAemMigjgPONVMLaWeb1RVjWdgRiJjSKvR02k-RSG4OS1mBZZcgBQhTwadjJTK3xJxVBNpy8ELWO7ypt44sxxHu923qJOnsVFRSBQ6yPXna7PirTWf1gVcz6JWaWXJG79JxGF1gyou9uZGPqIbpwx9AKz22tblYHhAPly8RVceMTKMkZz696WWn1zz7NUcLzD_3g2r2GgSxo4NGfpPWqBZYofxcT0Kt8UeK_ZW2c4U6WIWKhxCFTke4uuOdnYcAXwBKZkLP9nmatpw1cawOs7wwUBFG9zRxPCJXArkVuH3YKmvrLwBJ8lfwSe3nDV8gbnkKntBypu3XXefI6Ns_ighwAn3Ny6mww3hBxobBHjUzYauoWvxVmM8qaLO_RlrHUcRMLi7lUSnboyYao2zV3OFqTERSlvKM4WjzjmwILoEBWF3oZuHH9e3C4tOugBJEZ9xO7-sUR33T4XwoQt21e8Ts-iZbJwj8wSd6pGzZyhuARamdXpUxbObR0PfqSYM9fCNqxDzJoInlD4AtWFSLmNh4r5bU9izrGU1fJSYOgoq8_ZPeARzlKAZF6R8BMDC--Cj9089GdYOTeP6jQcB0B2LD6HTpYndIVwsrAxOHe3UQI1qClM3sd3xgu30klOM2xWR2KXCiT6sqTnKMRKTOzYrSVZahbcNamVhnUiYiLyWCigONzqhTB-gVcmonXHsLnOkjg2_vzZ4yblvifOE4WDMKJmOMWn_Dw2\"\r\nTrace ID: 41ab353a-0bfe-4cdf-9cd5-82168742b31a\r\nCorrelation ID: 950f9886-e7b9-4178-86fc-ed20b681b1e9\r\nTimestamp: 2016-01-29 10:40:06Z","error_codes":[50091],"timestamp":"2016-01-29 10:40:06Z","trace_id":"41ab353a-0bfe-4cdf-9cd5-82168742b31a","correlation_id":"950f9886-e7b9-4178-86fc-ed20b681b1e9"}
                                                                                       Timestamp: 2016-01-29 10:40:06Z ver:2.0.1-alpha
